language: csharp
mono: none
dotnet: 3.1

before_install:
- cd UserSettingsManager

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test UserSettingsManagerTests/UserSettingsManagerTests.csproj